version: "3.7"
volumes:
   mysql_data:
      driver: local
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.4
    environment: 
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports: 
      - "5432:5432"
  postgres_marketplace:
    container_name: postgres_marketplace_ifood
    image: postgres:12.4
    environment: 
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports: 
      - "5433:5432"
  
  mysql:
     container_name: mysql
     image: mysql:latest
     volumes:
        - mysql_data:/var/lib/mysql
     environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
     
  
  keycloak_ifood:
     container_name: keycloak_ifood
     image: jboss/keycloak:latest
     environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
     ports:
        - "8081:8080"
     depends_on:
        - mysql
  jaeger_ifood:
     container_name: jaeger_ifood
     image: jaegertracing/all-in-one:1.19
     ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "14268:14268"
        - "14250:14250"
        - "9411:9411"
  prometheus_ifood:
    container_name: prometheus_ifood
    image: prometheus-ifood
    network_mode: "host"
    
  grafana_ifood:
    container_name: grafana_ifood
    image: grafana/grafana:7.2.1
    network_mode: "host"
    
  artemis_ifood:
    container_name: artemis_ifood
    image: vromero/activemq-artemis:2.11.0
    network_mode: "host"
    environment:
       ARTEMIS_USERNAME: admin
       ARTEMIS_PASSWORD: admin
